spring:
  application:
    name: autenticacion_servicio
  datasource:
    url: jdbc:mysql://mysql:3306/viajes
    username: root
    password: passwdroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8004